### ISSUE TITLE
Environment Variables not Work in Docker-Compose

### ISSUE THREAD

**Issue by ClepToManix** [jusito/docker-ftb-alpine#3]
Hey,

just had a little issue with docker-compose file. The whole server works fine and the performance is very good. But i dont get my environment variables working with compose. I want to edit the server.properties with an environment variable. In the readme-section i see, that the variables needs to be written down with an _ and not an -. So in my point of view i had to add the variable in `- ALLOW_FLIGHT=TRUE`. Also tried to put the boolean inside "" but that also dont work. Here is the snipped of the relevant compose config:
```YAML
environment:
      - ALLOW_FLIGHT="true"`
```

Maybe my interpretation is totally wrong. As in information for you, this part is my only env-variable.
If more information is needed, please contact me.

Best regards,
Phil

**Comment by jusito** [comment]
sry that i reply that late, the env variables are case sensitive and allow_flight="true" is the correct usage.

**Comment by ClepToManix** [comment]
> sry that i reply that late, the env variables are case sensitive and allow_flight="true" is the correct usage.

Hey, no problem :) Ah okay, dont get it, that they are case sensitive. Now it works ;) Thank you very much 👍
